ci: Prepare for the 0.10.0 release
EnterpriseDB/terraform-provider-biganimal pull request #546
Opened 2024-04-24 14:16 UTC by wai-wong-edb

2024-04-29 08:01 UTC, edbamolvyavahare commented
LGTM

2024-04-29 08:01 UTC, edbamolvyavahare requested changes
Did we  add postGIS support to faraway replica resource ?

2024-04-29 08:36 UTC, wai-wong-edb commented
> Did we add postGIS support to faraway replica resource ?

No not yet

2024-05-08 10:16 UTC, edbamolvyavahare commented on CHANGELOG.md
> +## v0.10.0 (April 25. 2024)
need to update date

2024-05-08 14:54 UTC, edbamolvyavahare submitted a review, later dismissed
LGTM

2024-05-09 10:30 UTC, edbamolvyavahare approved these changes
LGTM

2024-05-13 13:23 UTC, merged