Support volumen snapshot in TF
EnterpriseDB/terraform-provider-biganimal pull request #564
Opened 2024-07-22 10:10 UTC by vishalsawale9

2024-07-25 15:51 UTC, wai-wong-edb requested changes

2024-07-25 15:51 UTC, wai-wong-edb commented on pkg/provider/resource_cluster.go
> +	VolumeSnapshot             types.Bool                         `tfsdk:"volume_snapshot_backup"`
Have VolumeSnapshot above Timeouts as timeouts as timeouts

2024-07-26 08:58 UTC, vishalsawale9 commented on pkg/provider/resource_cluster.go
> +	VolumeSnapshot             types.Bool                         `tfsdk:"volume_snapshot_backup"`
Done. Please check.

2024-07-26 09:21 UTC, wai-wong-edb commented
Looks good. But we can merge after I merged v1. After I merge v1 there may need to be some rebasing/merging changes

2024-08-02 13:32 UTC, edbamolvyavahare approved these changes
LGTM

2024-08-02 13:33 UTC, wai-wong-edb approved these changes

2024-08-05 14:29 UTC, wai-wong-edb commented
closed. Done in PR https://github.com/EnterpriseDB/terraform-provider-biganimal/pull/570

2024-08-05 14:29 UTC, closed without merging